k:
	./kill.sh
w:
	./write.sh
ws:
	./write_start.sh
wen:
	./write_en.sh

run_openchat:
	./run_openchat.sh
run_yichat:
	./run_yichat.sh
run_yichat9b:
	./run_yichat9b.sh
run_mixtral:
	./run_mixtral.sh
run_mixtral_moe:
	./run_mixtral_moe.sh
run_llama3:
	./run_llama3.sh
run_phi3:
	./run_phi3.sh

run_qwen:
	./run_qwenchat.sh
run_qwen8000:
	./run_qwenchat8000.sh
run_qwen8001:
	./run_qwenchat8001.sh
run_qwen8002:
	./run_qwenchat8002.sh
run_qwen8003:
	./run_qwenchat8003.sh
run_qwen8004:
	./run_qwenchat8004.sh
run_qwen8005:
	./run_qwenchat8005.sh